import type { Metadata } from "next";
import { Roboto, Lato } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap", // 👈 safe hydration
});

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap", // 👈 safe hydration
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          suppressHydrationWarning // 👈 avoids extension mismatch
          className={`${roboto.className} ${lato.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
